Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Title { get; set; }



        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [Column(TypeName = "text")]
        public string Description { get; set; }


        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Image { get; set; }



        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [Range(6, 30, ErrorMessage = "Il prezzo non deve essere inferiore a 6 euro")]
        public float Price { get; set; }


        public Pizza ()
        {

        }
        public Pizza(string title, string description, string image, float price)
        {
            this.Title = title;
            this.Description = description;
            this.Image = image;
            this.Price = price;
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using la_mia_pizzeria_static.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.Extensions.Hosting;


namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        PizzeriaDbContext db;

        public PizzaController() : base()
        {
            // Usiamo Data quindi DB
            // Metodo mostrato da Paolo per dichiarare soltanto una volta il nostro DB anziché di volta in volta 
            db = new PizzeriaDbContext();
        }
        //Read 
        public IActionResult Index()
        {
            // Usiamo Data quindi DB . Metodo Vecchio dove bisognava dichiarare di volta in volta il db in uso
            //PizzeriaDbContext db = new PizzeriaDbContext();


            // Usiamo Model
            List<Pizza> Pizzas = db.Pizzas.ToList();


            // In return possiamo passare un singolo argomento
            return View(Pizzas);
        }

        public IActionResult Detail(int id)
        {


            Pizza Pizzas = db.Pizzas.Where(p => p.Id == id).FirstOrDefault();

            return View(Pizzas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // Equivalente di CSRF di Laravel
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza Pizzas)
        {
            if (!ModelState.IsValid)
            {
                //return View(post);
                return View();
            }

            // Pusha nel db con .add
            db.Pizzas.Add(Pizzas);
            //Salva i cambiamenti effettuati
            db.SaveChanges();


            //Redirect alla Index quindi alla lista di pizze creata
            return RedirectToAction("Index");
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Razor()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Home Page";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome Pizza</th>
            <th scope="col">Descrizione</th>
            <th scope="col">Foto</th>
            <th scope="col">Prezzo</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Margherita</th>
            <td>Pacchettelle del Vesuvio I.G.P, mozzarella di bufala Campana, spolverata di Parmigiano Reggiano 36 mesi</td>
            <td>
                <img width="250px" height="150px" src="https://media-cdn.tripadvisor.com/media/photo-s/1d/6f/f4/c8/vesuvio.jpg">
            </td>
            <td>8.5</td>
        </tr>
        <tr>
            <th scope="row">Morte del Pistacchio</th>
            <td>Provola di Agerola, mortadella di Bologna, Pistacchio di Bronte</td>
            <td>
                <img width="250px" height="150px" src="https://images.dissapore.com/wp-content/uploads/2020/06/PHOTO-2020-06-18-15-04-33.jpg">
            </td>
            <td>10.5</td>
        </tr>
        <tr>
            <th scope="row">Domenicale</th>
            <td> Ragù Napoletano, polpettine di scottona, fior di latte di Agerola, Ciuffetti di ricotta</td>
            <td>
                <img class="myDimension" src="https://res.cloudinary.com/tf-lab/image/upload/restaurant/b7fbadd1-91cc-4057-98c1-cd9ed9a55cb5/acd6339d-6edd-40f3-83bf-63b8d3a475f3.jpg">
            </td>
            <td>10.5</td>
        </tr>
    </tbody>
</table>

Views/Pizza/Create.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}


@model Pizza 



<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Nuovo post</h1>
            </div>
            <form asp-controller="Pizza" asp-action="Create" method="post">

                <div class="mb-3">
                    <strong>Immagine:</strong>
                    <input asp-for="Image" class="d-block w-100" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Titolo:</strong>
                    <input asp-for="Title" class="d-block w-100" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Prezzo:</strong>
                    <input asp-for="Price" class="d-block w-100" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Contenuto:</strong>
                    <textarea asp-for="Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>

            </form>
        </div>
    </div>
</div>

Views/Pizza/Detail.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Pagina pizza";
}

@model Pizza


<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Dettagli post</h1>
            </div>
            <div class="post-single-image-container">
                <img class="myDimension" src="@Model.Image">
            </div>
            <p>
                <strong>Titolo:</strong>
                @Model.Title
            </p>
            <p>
                <strong>Descrizione:</strong>
                @Model.Description
            </p>
            <p>
                <strong>Prezzo:</strong>
                @Model.Price
            </p>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Pagina pizza";
}

@model List<Pizza> 

@if(Model.Count() == 0){
    <h3 class="text-center">Al momento non ci sono pizze disponibili</h3>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Foto</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrizione</th>
                <th scope="col">Prezzo</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
                @foreach (Pizza Pizza in Model)
                {
                <tr>
                    <td>@Pizza.Id</td>
                    <td class="image">
                        <img class="myDimension" src="@Pizza.Image">
                    </td>
                    <td class="title">@Pizza.Title</td>
                    <td class="description">
                          
                        <button type="button" class="btn btn-primary">
                            <a href="@Url.Action("Detail",new {id = Pizza.Id})">Vai ai Dettagli</a>
                        </button>
                    </td>
                    <td class="price">
                            @Pizza.Price
                    </td>
                </tr>
                }
        </tbody>
        </tbody>
    </table>
}

Views/Razor/Razor.cshtml
@{
    Layout = "_LayoutRazor";
    ViewData["Title"] = "Razor Snack";


    // Var Snack 1

    string nome = "Francesco";
    string cognome = "Marra";

    // Var Snack 2 
    int numberS2 = 10;

    // Var Snack 3
    string text = "nel mezzo del cammin di nostra vita";
    int iS3 = 0;

    // Area test

    foreach(Char letter in text)
    {
        if(letter == 'a')
        {
            iS3++;
        }
    }

    // Area test fine
}

<h1> Razor Snacks 1 </h1>

<h2> Ciao @nome @cognome</h2>

<h1> Razor Snacks 2</h1>

<h2>
    @for (var i = 0; i <= @numberS2; i++)
    {
        <span>  - @i  </span>
    }
</h2>

<h1>Razor Snacks 3 </h1>

<h2>
    @text contiene @iS3;

</h2>

<h1>Razor Snack 4</h1>


    
      
<h2>
    @{
        List<int> NumeriInteri = new List<int>(20);

      

        for (int i = 0; i < 20; i++)
        {
            int numeroCasuale = new Random().Next(1, 91);

     
            if (numeroCasuale > 20 && numeroCasuale < 70)
            {
                NumeriInteri.Add(numeroCasuale);

               <span> @numeroCasuale </span>
            }
        }
    }


</h2>


<h1> Razor Snack 5</h1>

<h2>
        La data e l'ora di oggi è : @DateTime.Now
 </h2>


<h1> Razor Snack 6 </h1>


<h2>
    @{
        //Dichiaro la giornata di oggi
        DateTime today = DateTime.Now;

        //Dopo averla dichiarata, scalo con AddDays 
        DateTime WeekAgo = today.AddDays(-7);
        //Dichiaro un Anno in più con AddYears
        DateTime YearsAgo = today.AddYears(1);
        // Dichiaro facendo "Anno" "Mese" "Giorno"
        var year = YearsAgo.ToString("yyyy MMMM dddd");
        @year
    }
        </h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 1000 Gourmet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Pizza" asp-action="Index">1000 Gourmet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Le nostre Pizze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Razor">Razor</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Create">Aggiungi una Pizza</a>
                        </li>
                           
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutRazor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 1000 Gourmet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>